# Generated by Django 4.2.11 on 2026-05-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('duracion_estimada', models.DurationField(help_text='Duración estimada del viaje (hh:mm:ss)')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['origen', 'destino'],
                'unique_together': {('origen', 'destino')},
            },
        ),
    ]
