# Generated by Django 4.2.11 on 2026-05-13 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('tipo_servicio', models.CharField(choices=[('economico', 'Económico'), ('ejecutivo', 'Ejecutivo'), ('cama', 'Cama'), ('doble_piso', 'Doble Piso')], default='economico', max_length=20)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='flota.empresa')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'ordering': ['empresa', 'placa'],
            },
        ),
    ]
