# Generated by Django on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(
                choices=[
                    ('programado', 'Programado'),
                    ('en_embarque', 'En embarque'),
                    ('en_camino', 'En camino'),
                    ('finalizado', 'Finalizado'),
                    ('cancelado', 'Cancelado'),
                    ('en_curso', 'En curso'),
                    ('completado', 'Completado'),
                ],
                default='programado',
                max_length=20,
            ),
        ),
    ]
