# Generated by Django 4.2.11 on 2026-05-16 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_pasajero'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pasajero',
            new_name='cuentas_pas_dni_b51520_idx',
            old_name='cuentas_pasajero_dni_idx',
        ),
    ]
