# Generated by Django 4.2.11 on 2026-05-16 01:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_rename_cuentas_pasajero_dni_idx_cuentas_pas_dni_b51520_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=9, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 9 dígitos', regex='^\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener exactamente 8 dígitos', regex='^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 9 dígitos', regex='^\\d{9}$')]),
        ),
    ]
