# Generated by Django 4.2.11 on 2026-05-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_alter_pasajero_telefono_alter_usuario_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=120)),
                ('marca', models.CharField(max_length=30)),
                ('ultimos_4', models.CharField(max_length=4)),
                ('mes_expiracion', models.PositiveSmallIntegerField()),
                ('anio_expiracion', models.PositiveSmallIntegerField()),
                ('es_principal', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarjeta de cliente',
                'verbose_name_plural': 'Tarjetas de clientes',
                'ordering': ['-es_principal', '-creada_en'],
            },
        ),
    ]
