# Generated by Django 6.0.4 on 2026-05-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('servicio', models.CharField(choices=[('economico', 'Económico'), ('bus_cama', 'Bus Cama'), ('bus_cama_vip', 'Bus Cama VIP')], max_length=30)),
                ('precio_normal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_promocional', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagen', models.CharField(blank=True, max_length=300)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
