# Generated by Django for encomiendas.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flota', '0002_update_tipo_servicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=14, unique=True)),
                ('remitente_nombres', models.CharField(max_length=150)),
                ('remitente_dni', models.CharField(max_length=8)),
                ('remitente_telefono', models.CharField(max_length=9)),
                ('destinatario_nombres', models.CharField(max_length=150)),
                ('destinatario_dni', models.CharField(blank=True, max_length=8)),
                ('destinatario_telefono', models.CharField(max_length=9)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('registrado', 'Registrado'), ('en_transito', 'En tránsito'), ('en_agencia_destino', 'En agencia destino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], db_index=True, default='registrado', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encomiendas', to='flota.empresa')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encomiendas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encomienda',
                'verbose_name_plural': 'Encomiendas',
                'ordering': ['-creado_en'],
                'indexes': [
                    models.Index(fields=['codigo'], name='encomiendas_codigo_4a82a6_idx'),
                    models.Index(fields=['remitente_dni'], name='encomiendas_remiten_d405ee_idx'),
                ],
            },
        ),
    ]
