# Generated by Django 4.2.11 on 2026-05-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomiendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomienda',
            name='condicion_pago',
            field=models.CharField(choices=[('pagado_origen', 'Pagado en agencia'), ('cobro_destino', 'Paga al recoger')], default='pagado_origen', max_length=20),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('plin', 'Plin'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='pagado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
