# Generated by Django 4.2.11 on 2026-05-18 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encomiendas', '0003_backfill_pagado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomienda',
            name='clave_recojo',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='entregado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encomiendas_entregadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='recogido_por_dni',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='recogido_por_nombres',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
