# Generated by Django 4.2.11 on 2026-05-18 03:11

from django.db import migrations, models


def backfill_ordenes(apps, schema_editor):
    Encomienda = apps.get_model('encomiendas', 'Encomienda')
    for encomienda in Encomienda.objects.filter(numero_orden='').only('id'):
        encomienda.numero_orden = f'ORD{encomienda.id:09d}'
        encomienda.codigo_orden = f'{(encomienda.id * 137) % 1000000:06d}'
        encomienda.codigo_verificacion_pago = f'{(encomienda.id * 7919) % 1000000:06d}'
        encomienda.save(update_fields=['numero_orden', 'codigo_orden', 'codigo_verificacion_pago'])


class Migration(migrations.Migration):

    dependencies = [
        ('encomiendas', '0006_backfill_entregas_antiguas'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomienda',
            name='codigo_orden',
            field=models.CharField(blank=True, default='', editable=False, max_length=6),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='codigo_verificacion_pago',
            field=models.CharField(blank=True, default='', editable=False, max_length=6),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='numero_orden',
            field=models.CharField(blank=True, default='', editable=False, max_length=12),
        ),
        migrations.RunPython(backfill_ordenes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='encomienda',
            name='numero_orden',
            field=models.CharField(blank=True, default='', editable=False, max_length=12, unique=True),
        ),
    ]
