# Generated by Django 4.2.11 on 2026-05-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomiendas', '0007_encomienda_codigo_orden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='condicion_pago',
            field=models.CharField(choices=[('pagado_origen', 'Pagado en agencia'), ('pagado_web', 'Pagado en web'), ('cobro_destino', 'Paga al recoger')], default='pagado_origen', max_length=20),
        ),
    ]
