# Generated by Django 4.2.11 on 2026-05-13 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viajes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_boleto', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_asiento', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('usado', 'Usado')], default='reservado', max_length=20)),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('pasajero', models.ForeignKey(limit_choices_to={'rol': 'pasajero'}, on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='viajes.viaje')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['-fecha_compra'],
                'unique_together': {('viaje', 'numero_asiento')},
            },
        ),
    ]
