# Generated by Django 4.2.11 on 2026-05-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='apellido_pasajero',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='boleto',
            name='email_pasajero',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='boleto',
            name='nombre_pasajero',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='boleto',
            name='num_doc',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='boleto',
            name='telefono_pasajero',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='boleto',
            name='tipo_doc',
            field=models.CharField(blank=True, default='DNI', max_length=30),
        ),
    ]
