# Generated by Django 4.2.11 on 2026-05-14 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0002_boleto_apellido_pasajero_boleto_email_pasajero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='pasajero',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'pasajero'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to=settings.AUTH_USER_MODEL),
        ),
    ]
