# Generated by Django 4.2.11 on 2026-05-16

from django.db import migrations, models
import django.db.models.deletion
import apps.ventas.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
        ('ventas', '0003_alter_boleto_pasajero'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_operacion', models.CharField(default=apps.ventas.models.generar_numero_operacion, max_length=10, unique=True)),
                ('asientos_str', models.CharField(max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('qr_payload', models.TextField(blank=True, default='')),
                ('qr_imagen_base64', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_qr', to='viajes.viaje')),
            ],
            options={
                'verbose_name': 'Pago QR',
                'verbose_name_plural': 'Pagos QR',
                'ordering': ['-creado_en'],
                'indexes': [
                    models.Index(fields=['codigo'], name='ventas_pago_codigo_2d3e8a_idx'),
                    models.Index(fields=['numero_operacion'], name='ventas_pago_numero_42c0ac_idx'),
                    models.Index(fields=['estado'], name='ventas_pago_estado_f335a3_idx'),
                ],
            },
        ),
    ]
