# Generated by Django 4.2.11 on 2026-05-16 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_pagoqr'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pagoqr',
            new_name='ventas_pago_codigo_0d4a37_idx',
            old_name='ventas_pago_codigo_2d3e8a_idx',
        ),
        migrations.RenameIndex(
            model_name='pagoqr',
            new_name='ventas_pago_numero__32c7d5_idx',
            old_name='ventas_pago_numero_42c0ac_idx',
        ),
        migrations.RenameIndex(
            model_name='pagoqr',
            new_name='ventas_pago_estado_b15ae9_idx',
            old_name='ventas_pago_estado_f335a3_idx',
        ),
    ]
