# Generated by Django 6.0.4 on 2026-05-16 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0001_initial'),
        ('ventas', '0005_rename_ventas_pago_codigo_2d3e8a_idx_ventas_pago_codigo_0d4a37_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='promo_aplicada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos', to='promociones.promocion'),
        ),
        migrations.AddField(
            model_name='pagoqr',
            name='promo_aplicada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_qr', to='promociones.promocion'),
        ),
    ]
