# Generated by Django on 2026-05-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viajes', '0002_alter_viaje_estado'),
        ('ventas', '0006_boleto_promo_aplicada_pagoqr_promo_aplicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='estado',
            field=models.CharField(
                choices=[
                    ('confirmado', 'Confirmado'),
                    ('pendiente', 'Pendiente'),
                    ('cancelado', 'Cancelado'),
                    ('reprogramado', 'Reprogramado'),
                    ('anulado', 'Anulado'),
                    ('reservado', 'Reservado'),
                    ('usado', 'Usado'),
                ],
                default='pendiente',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='boleto',
            name='estado_pago',
            field=models.CharField(
                choices=[('confirmado', 'Confirmado'), ('pendiente', 'Pendiente')],
                default='confirmado',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='boleto',
            name='metodo_pago',
            field=models.CharField(
                choices=[
                    ('efectivo', 'Efectivo'),
                    ('yape', 'Yape'),
                    ('plin', 'Plin'),
                    ('tarjeta', 'Tarjeta'),
                    ('transferencia', 'Transferencia'),
                ],
                default='yape',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='boleto',
            name='vendido_por',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='boletos_vendidos_panel',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name='CancelacionBoleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasajero_nombre', models.CharField(max_length=180)),
                ('motivo', models.TextField()),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='aprobado', max_length=20)),
                ('monto_devuelto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancelaciones', to='ventas.boleto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelaciones_boletos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cancelacion de boleto',
                'verbose_name_plural': 'Cancelaciones de boletos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ReprogramacionBoleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento_anterior', models.PositiveSmallIntegerField()),
                ('asiento_nuevo', models.PositiveSmallIntegerField()),
                ('motivo', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reprogramaciones', to='ventas.boleto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprogramaciones_boletos', to=settings.AUTH_USER_MODEL)),
                ('viaje_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos_reprogramados_origen', to='viajes.viaje')),
                ('viaje_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos_reprogramados_destino', to='viajes.viaje')),
            ],
            options={
                'verbose_name': 'Reprogramacion de boleto',
                'verbose_name_plural': 'Reprogramaciones de boletos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
